### ISSUE TITLE
socket SSL error

### ISSUE THREAD

**Issue by Frogsecurity** [get-get-get-get/PowerProxy#3]
Currently running into this error on the handling side. 

I did not modify the powershell script. 

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/Desktop/tools/PowerProxy-master/reverse_proxy_handler.py", line 227, in listen_for_reverse
    reverse_socket = self.ssl_context.wrap_socket(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1066, in _create
    self._sslobj = self._context._wrap_socket(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLError: Cannot create a server socket with a PROTOCOL_TLS_CLIENT context (_ssl.c:798)

**Comment by bcarlett** [comment]
Might be a be late on that one, but it looks like a python version problem.
It should be working with Python 3.9.
